sudo: required
language: minimal
services:
  - docker

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "tn1AHTidz5gVTuGFUMH7NJt9mOcFRwOeWntwZ0oR3ETB6t40xxYwnX4cRXXE8ph++SGY4dmbBxwRcSPy2j0wI4dVyt8a0zeWqEes0J783go1/3sa1z9O0HF00PKrmxa2IJoae1BTTZT7juhr1D7e/JHKa6QFD8LlOBx0VQz0JPdNDQ0ukACKLp6yRC+ODLP349RkMn/7f/tINslXjd41q0Hed87g8X/tr3YBDJgbGEqdjOLlw5L4ZKYmo0osdTlTs5VVnpwST/EJuEbZ/yLSjXS4MHztUitGchUmRT3k4Spcmez/pHgo5EXCM7uKswZ/Kehle51Empa11Y4EDhac4p6XruY9F2PH/e5LAy7RezqHUDsYNe6ely5jph/a4zLl25JPUvsUe8/297JxDVu1CRJqRGKxioZdjnQ40IGnHs6oXNGcvvWHd/YSJPNaTtNJuuGEf8tsyfDYYmDUcxr0d62VDJ7B+1vZNSt6NZQToNEmnlJn9nmDETpI1iqEDcm6CJtRS6uAINeuwlGywaeAWhy+TShVMhWfodH1jPnGB6u4TaxQ0E5wRtFvZoAuiHh6gsvco+FvHd0tnQUNy7HLvze2EdorDNDbBMAVYvcfzgskydn5fUNvcRNuV+xFFNVB8XLSGHhzftObop9+ySGMDKGaat6cG8ov/8W6wRpMd7U="
    # AWS_SECRET_ACCESS_KEY
    - secure: "mk/nAEWODZCZU6IjeTN8b4HwxJHlFIfYj2b3lrVn07JHeBQe9Cz4bfRAzo+6BhTlIkpD7/o1fXwhA8AVDANDVc8EvTVcluJo51FK1BGzY49tmel7Ib07OBATtC7HSMjzQ1anO03GrT3szAaM2tLZz32ARheBK6BxenLtIOMJLdDpe9NTYzkDuWDu+JWK9rGFxRnVt219rfhLFZzM1b0DWZmFypDsXiv8j4SsNlM0qj5r99g+CX3vzVEr+HzWS47GZ9Z18p+RYe7HFkkvxgxtO3MZ3Wk12er+Ab+faJtYLV+VuLaSglcufFL+TaxXwzzNkatFInYgp51nRsZH6tOV6WpNkpZyY46UpcgtFmyLiMgH4nZe6v6YMl+ydDtTsF3gBh6WNYJIO2qyMM7nKukRmpx4h44GxcGxI/77RSAhpL97wR81oM3M8mVqoODH2AEDz0mESAZcqwSFVIoIVWAHuyICcec10JJ/1zdkMcwyU8tkC/KGK7K0g80Zb2ddcOwXaiD2V91lf6A7fTX+0oCE7SG/GLJWDmStWETE5r4P8FXzRpKVAGFtDOlcxkxJdAfLeIXM0ukK3+2ib/NaL2dvCI7kuHJXyTNEP7rYQstsfnM6LZgKIuLhex28oD21vH4htt1FfOkhKmdzUCexNTD+dlPxQiN0z4g9yTAKeu7OGt4="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="clamav"

script:
  - export DOCKER_TARGET="${ECR_REPO}/${ARTIFACT_NAME}:ci-${TRAVIS_BUILD_NUMBER}"
  - docker build -t ${DOCKER_TARGET} .

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
  on:
    all_branches: true
